### PR TITLE
CDN and audio tag optimization

### PR DESCRIPTION
**Pull request by ShallowAi**
optimized js and css delivr, and audio preload metadata increased page loading time.

PLZ Remove my PR CNAME and manifest.json edition.

### CODE REVIEW

**Comment by Aceship** [comment]
Apparently all the bootstrap thing doesnt work on that one 
i think its because the bootstrap that were forked at first was edited 
might need to check later

**Comment by ShallowAi** [comment]
> Apparently all the bootstrap thing doesnt work on that one
> i think its because the bootstrap that were forked at first was edited
> might need to check later

Checked
`bootstrap.min.css` SHA1: 895125A4522A3B10EE7ADA06EE6503587CBF95C5 same content.
`bootstrap.min.js` Not same sha-1 but have same content.
`jquery.min.js` upgrade from 3.4.0 to 3.4.1
`popper.js` upgrade from very old version to 1.16.1
`font-awesome.min.css` both from cdn are same content.

All listed above have been tested.

**Comment by Aceship** [comment]
does it work on your part ?
tbh i only checked it by directly opening the html file

**Comment by ShallowAi** [comment]
it works online, because '//' equals use same origin, local will use file://, at web will use http:// or https://
if don't want to same origin you can change // to http:// or https://.

`A few moments ago, i fixed my typo included wrong type of popper.min.js.`

**Comment by Aceship** [comment]
Ah nice, i didnt know that // part means that

btw about the audio part `preload="metadata"` is deleted, doesnt that means all the audio gonna be downloaded at first ?

tbh idk whats the default of that part

**Comment by ShallowAi** [comment]
> Ah nice, i didnt know that // part means that
> 
> btw about the audio part `preload="metadata"` is deleted, doesnt that means all the audio gonna be downloaded at first ?
> 
> tbh idk whats the default of that part

sorry, i checked wiki it said preload can be [none/meta/auto], in there i support change
`preload="metadata"` to `preload="none"`.
in this way can make audio download when you click the play button.

**Comment by Aceship** [comment]
> sorry, i checked wiki it said preload can be [none/meta/auto], in there i support change
> `preload="metadata"` to `preload="none"`.
> in this way can make audio download after you clicked the play button.

isnt its should be still `preload="metadata"` so it downloads the length info, but not the audio itself ?
so anyone would know how long it is before actually downloading the audio

**Pull request merged**
