### PR TITLE
Reorder Recruitment tags in order of appearance

### PR DESCRIPTION
**Pull request by az3**
In the recruitment, the tags appear in a specific order. For example Survival tag always comes before AoE. To simulate this behaviour, tags are updated. 

With this commit, only the ordering is changed.

### CODE REVIEW

**Comment by az3** [comment]
@Aceship Hello, do you have any plans to check this request?

The outcome is identical, only the ordering is updated with this change. So it is easier to track the tags.

For example for this recruitment (in game menu) options;
image

Web site will display tags in the same order as they appear in game;
image

Thanks for your concern.

**Comment by Aceship** [comment]
> The outcome is identical, only the ordering is updated with this change. So it is easier to track the tags.

ngl i havent been checking the recruit stuff

does it also have the same order on other language ?

i'll check the chinese one for now

**Comment by Aceship** [comment]
seems like its okay on chinese client, still dont know about the other language tho

**Comment by az3** [comment]
> does it also have the same order on other language ?

I used "Ptilop.sys" from Android, and it also shows them in the same order. It is safe to assume they will be same in TW & JP, too.

**Comment by Aceship** [comment]
> I used "Ptilop.sys" from Android, and it also shows them in the same order. It is safe to assume they will be same in TW & JP, too.

ah okay, i guess its fine, thanks for the pr 👍

**Pull request merged**
