### PR TITLE
[AKHRCHARS] akhrchars: add a filtering at "Browse Grid"

### PR DESCRIPTION
**Pull request by arthus-leroy**
Phew. This one was tough. It was asked in Issue #25.

Sooooo...
This commit brings a new dimension to "Operator search". It lets you search according to a wide variety of criteria in a powerful manner. More criteria can be added without much problem.

Here are some problems to fix now or later :
* ~The icons for sort-asc and sort-desc must changed as they are most likely copyrighted (priority high)~
* Abused a bit on the css, it should be placed at the right place (having css inside a style tag is really an awful practice, priority medium)
* ~There is a filthy eval (under a TODO) as trigger or click didn't work on "onclick". It should be replaced if possible (priority medium)~
* It would be nice to have icons for the subclasses, but my skills at PS/GIMP sucks, so eh... (priority medium, ~not really a problem~)
* I'm not satisfied with the dirty hack of the AoE Healers (under a NOTE), but getting something clean would require to rethink the data of character_table.json (priority medium-low)
* The sort use discrete values such as atk, def, hp and hence can't be combined if the heaviest stat is different between 2 operators. If the difference is non-null, any lower-weighted stat get lost in the weighting of the whole, ~but do we actually care ?~ It is possible to completely remove the possibility to choose several sorting options by doing something similar to clearFilter at each switchState call (priority low)
* The css of the whole would need to be revised as UI (css and such) is hardly my forte (priority low).

### CODE REVIEW

**Comment by Aceship** [comment]
i guess its getting too crowded
probably need some hiding all the filter at default 🤔 

also for the sort-asc sort-desc just use the fontawesome thing 
https://fontawesome.com/icons/sort-amount-up?style=solid
https://fontawesome.com/icons/sort-amount-down-alt?style=solid

**Comment by Aceship** [comment]
for the subclass, tbh you could check tl-attacktype for it, and probably add extra subclass stuff on it

**Comment by arthus-leroy** [comment]
> for the subclass, imo you could check tl-attacktype for it, and probably add extra subclass stuff on it

tl-attacktype is merely a translation of description. I'm talking about something at the same level than skills/traits/talents.

> i guess its getting too crowded
> probably need some hiding all the filter at default

Was thinking something like that, but it can be a hassle to unfold each section. Hard to tell what would be the best design

**Comment by Aceship** [comment]
for css stuff, i'll tidy it up later after you liked the result 

also for the eval fix, imo just use extra data
image
image

for the hide stuff, personally just toggle for all the whole stuff beside class 
image

**Comment by Aceship** [comment]
> tl-attacktype is merely a translation of description. I'm talking about something at the same level than skills/traits/talents.

i guess more extra data needed for that, like a list of subclass with the chara name inside 

but personally i prefer hacky stuff, so you dont need to update them every new chara update

**Comment by arthus-leroy** [comment]
Will add the collapsible tomorrow (in ~6-8h).

**Comment by Aceship** [comment]
i forgot about this, i'll check later when i got time

**Comment by Aceship** [comment]
~if you have time, probably add gender filter too, in case someone wants too see just male or just female chara~

**Comment by arthus-leroy** [comment]
Ok, gonna add that real quick

**Comment by arthus-leroy** [comment]
Done ~and damn, there are 5.5x more females than males :lappKek:~

**Comment by Aceship** [comment]
Finally have time doing it

**Comment by arthus-leroy** [comment]
@Aceship Remember to close #25 too

**Pull request merged**
