### PR TITLE
akmatuses: inverse material search based on akhr

### PR DESCRIPTION
**Pull request by arthus-leroy**
~~Some operators' pictures are missing* (medium priority)~~ problem solved
~~Some material icons behave a little wonky (low priority)~~ problem solved
This page only support English language and region (low priority)
Some optimizations could be made to not actualize everything at any change (very low priority, quite code heavy)

~~Waiting for code review and discussion on the current problems.~~ ready to be merged

~~* this is partially caused by the names of some operators being in Russian instead of their ingame name (need to be discussed)~~

### CODE REVIEW

**Comment by Aceship** [comment]
> this is partially caused by the names of some operators being in Russian instead of their ingame name (need to be discussed)

there's a `tl-unreadablename.json` for russia name, it might fix your problem

**Comment by Aceship** [comment]
>Some operators' pictures are missing* (medium priority)

if possible, use the other folder `(avatars folder)` instead of chara, since it was mainly old recruit pic ~that were never fixed~

**Comment by Aceship** [comment]
>Some material icons behave a little wonky (low priority)

use `object-fit: contain;` on the img style / css

**Comment by arthus-leroy** [comment]
> > this is partially caused by the names of some operators being in Russian instead of their ingame name (need to be discussed)
> 
> there's a `tl-unreadablename.json` for russia name, it might fix your problem

I was wondering if it wouldn't be better to transition to using English names as the game uses English names. It always troubled me in akhr.

**Comment by Aceship** [comment]
>I was wondering if it wouldn't be better to transition to using English names as the game uses English names. It always troubled me in akhr.

personally both okay, personally i'll add both english and russia name

**Comment by arthus-leroy** [comment]
Only thing left to discuss is the need of any other language (cn, kr, jp) or region (cn). Will there be a need at some point or can this be safely dropped for this page ?

**Comment by Aceship** [comment]
>Only thing left to discuss is the need of any other language (cn, kr, jp) or region (cn). Will there be a need at some point or can this be safely dropped for this page ?

well, you can release english page first, and then add other language later

**Comment by arthus-leroy** [comment]
The page can be merged. I leave the menu and other misc to your discretion.

**Comment by Aceship** [comment]
okay, thanks for the hard work

i'll check it later and do some tweaks

**Comment by Aceship** [comment]
Pull request should've done, but somehow its still not closed, probably i did something wrong with it

thanks @arthus-leroy for the contribution, the material use should be available in `calculator > Material total usage`

**Pull request closed without merging**
